name = "banyan"
license = "MIT"
licenselink = "https://github.com/swawai/banyan/blob/master/LICENSE"
description = "A Explorer-like Hugo theme."
homepage = "https://github.com/swawai/banyan/"
tags = ["blog", "minimalist"]
features = []
min_version = "0.120.0"

[author]
  name = "swaw"
  homepage = "swaw.com"
